apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: quarkus-github-artifactory-gitops-repository
spec:
  url: https://github.com/RHTAP-RHDH/quarkus-github-artifactory-gitops